export type TxType = 'INCOME' | 'EXPENSE' | 'ALLOCATION';
export type CategoryType = 'INCOME' | 'EXPENSE';

export interface User {
  id: string;
  name: string;
  email: string;
  passwordHash: string;
  salt: string;
  createdAt: string;
}

export interface Pocket {
  id: string;
  name: string;
  icon: string;
  color: string;
  /** Monthly spending budget. 0 means no budget. */
  budget: number;
  isLocked: boolean;
  /** Savings pockets are excluded from the daily spending limit. */
  isSavings: boolean;
  archived: boolean;
  createdAt: string;
}

export interface Category {
  id: string;
  name: string;
  type: CategoryType;
  icon: string;
  color: string;
}

/**
 * INCOME adds money to the unallocated balance (pocketId null).
 * ALLOCATION moves money from the unallocated balance into a pocket.
 * EXPENSE removes money from a pocket.
 */
export interface Transaction {
  id: string;
  type: TxType;
  amount: number;
  pocketId: string | null;
  categoryId: string | null;
  /** Local date, YYYY-MM-DD */
  date: string;
  note: string;
  createdAt: string;
  /** Set when the transaction was generated by a recurring rule. */
  recurringId?: string;
  /** Local file URI of the receipt/item photo taken for an expense. */
  photoUri?: string;
  /** Nutrition estimate when the expense photo shows food. */
  food?: FoodAnalysis;
}

/** Nutrition estimate for one photographed dish. Amounts are per portion shown in the photo. */
export interface FoodAnalysis {
  name: string;
  portion: string;
  weightGrams: number;
  calories: number;
  carbsG: number;
  proteinG: number;
  fatG: number;
  sodiumMg: number;
  sugarG: number;
  saturatedFatG: number;
  micros: { name: string; amount: string; akgPct: number }[];
  vegan: boolean;
  vegetarian: boolean;
  glutenFree: boolean;
  /** 0 = not spicy, 3 = very spicy. */
  spicyLevel: number;
  /** 1-100, higher is healthier. */
  healthScore: number;
  healthNote: string;
}

export interface Transfer {
  id: string;
  fromPocketId: string;
  toPocketId: string;
  amount: number;
  date: string;
  note: string;
  createdAt: string;
}

export interface Goal {
  id: string;
  name: string;
  icon: string;
  targetAmount: number;
  /** Used only when the goal is not linked to a pocket. */
  currentAmount: number;
  targetDate: string | null;
  pocketId: string | null;
  createdAt: string;
}

export type Frequency = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';

/**
 * A template that creates an INCOME or EXPENSE transaction on a schedule.
 * Occurrence n falls on startDate + n * frequency, so monthly rules that start
 * on the 31st stay on the last day of short months without drifting.
 */
export interface RecurringRule {
  id: string;
  type: 'INCOME' | 'EXPENSE';
  amount: number;
  /** Required for EXPENSE, null for INCOME. */
  pocketId: string | null;
  categoryId: string | null;
  note: string;
  frequency: Frequency;
  startDate: string;
  /** Number of occurrences already recorded. */
  occurrences: number;
  /** Optional last date (inclusive). */
  endDate: string | null;
  active: boolean;
  createdAt: string;
}

export interface UserData {
  pockets: Pocket[];
  categories: Category[];
  transactions: Transaction[];
  transfers: Transfer[];
  goals: Goal[];
  recurring: RecurringRule[];
}

export interface Settings {
  theme: 'system' | 'light' | 'dark';
  dailyReminder: boolean;
  /** Minutes after midnight. */
  reminderTime: number;
  budgetAlerts: boolean;
  recurringAlerts: boolean;
  /** Gemini API key (free tier) used for food photo analysis. Empty disables it. */
  geminiApiKey: string;
}
